name: gitflow-action
description: A GitHub Action that automatically creates and merges pull requests between specified branches..
author: Bruno Logerfo, Dawid Janik

branding:
  icon: git-merge
  color: white

inputs:
  github-token:
    description: The `GITHUB_TOKEN` secret.
    required: true
  release:
    description: The `release` branch.
    required: false
    default: release
  dev:
    description: The `dev` branch.
    required: false
    default: dev
  master:
    description: The `master` branch.
    required: false
    default: master
  label:
    description: The pull request label.
    required: false
    default: gitflow
  auto-merge:
    description: If `true`, will try to automatically merge pull requests. Can also be set to `pull_request_review`, `check_run`, `push`, or a comma-separated combination of these values to only merge when handling the named events.
    default: true
  require-merge:
    description: If an attempted merge fails, the action is considered to have failed.
    default: false

runs:
  using: 'node12'
  main: 'dist/index.js'
